### ISSUE TITLE
serving font-awesome or font glyphicons

### ISSUE THREAD

**Issue by micha1983** [me-no-dev/ESPAsyncWebServer#177]
HI,
i try to server font files from spiff. but when i serve them locally from the ESP8266 i get an 404 error.

Is anybody able to server woff, tff or woff2 fonts with this project and can help me?

I included the css file inside of the index.html like this

`<link rel="stylesheet" href="css/font-awesome.min.css">`

and i get following 

`GET http://192.168.16.124/fonts/fontawesome-webfont.woff2?v=4.7.0 
192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.woff?v=4.7.0
192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.ttf?v=4.7.0
192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.woff?v=4.7.0
192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.ttf?v=4.7.0`

Can anybody help me out. sorry i'm pretty new to this stuff.
maybe there is something principal wrong.

**Comment by nuljon** [comment]
Try leading with a slash in your url ...
href="/css/font-awesome.min.css
Sent from my Boost Mobile Phone.
-------- Original message --------From: micha1983 <notifications@github.com> Date: 6/15/17  2:03 PM  (GMT-08:00) To: me-no-dev/ESPAsyncWebServer <ESPAsyncWebServer@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [me-no-dev/ESPAsyncWebServer] serving font-awesome or font glyphicons
  (#177) 
HI,

i try to server font files from spiff. but when i serve them locally from the ESP8266 i get an 404 error.
Is anybody able to server woff, tff or woff2 fonts with this project and can help me?
I included the css file inside of the index.html like this
<link rel="stylesheet" href="css/font-awesome.min.css">
and i get following
GET http://192.168.16.124/fonts/fontawesome-webfont.woff2?v=4.7.0 192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.woff?v=4.7.0 192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.ttf?v=4.7.0 192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.woff?v=4.7.0 192.168.16.124/:1 Failed to decode downloaded font: http://192.168.16.124/fonts/fontawesome-webfont.ttf?v=4.7.0
Can anybody help me out. sorry i'm pretty new to this stuff.

maybe there is something principal wrong.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/me-no-dev/ESPAsyncWebServer","title":"me-no-dev/ESPAsyncWebServer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/me-no-dev/ESPAsyncWebServer"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"serving font-awesome or font glyphicons (#177)"}],"action":{"name":"View Issue","url":"https://github.com/me-no-dev/ESPAsyncWebServer/issues/177"}}}

**Comment by micha1983** [comment]
a slash in front doesn't change anything.
it's only with fonts. alle other files will be served nicely.

**Comment by micha1983** [comment]
If I implement this with a path from a different server it works fine. so something is wrong in serving this files with ESPAsyncWebserver

**Comment by micha1983** [comment]
i found it.

the pathname is too long. i removed everywhere -webfont and than it worked.
