### ISSUE TITLE
AsyncWebSocket WS_MAX_QUEUED_MESSAGES too low, app totally broken

### ISSUE THREAD

**Issue by philbowles** [me-no-dev/ESPAsyncWebServer#489]
I'm glad this doesn't crash any more due to low heap, but you have swung back too far the other way.  8 Socket messages is pretty much useless for anything other than the minute hand of an analog clock...AND it took me a hell of a long time to hack through the code to find that after my app suddenly broke in a BIG way as socket messages are now silently discarded with no warning, no errors and no way to know. It's a pretty poor show, to be honest.

Do I now have to implement some ack / nak mechanism for every one of my socket messages just so I know it got received - I kinda thought that was what TCP was for...? If my app relies upon socket delivery to work - which it does - it is now severely and utterly broken, with a HUGE amount of work to re-engineer.

I shall continue to sift through that code to see if you have provided an API to tell when its safe to send without the message just disappearing...otherwise I'm totally screwed. May I suggest the following may go some way to offset the damage your "fix" has done:

1) Immediately update the docs and at least let people know how limited this feature now is
2) add / change an API that - for- example returns true if your message will fail so at least you can hold off and retry once the queue of 8 socket messages has emptied...and an async way to tell when that has happened
3) An easy way for the user to set / change the limit and his/her own decisions about how much ram is worth spending....

I'm sorry if this comes across as "a bit strong" but after nearly two days of frustration to find this I am now watching while about 12-18months of work and 4-5000 lines of code have just gone down the toilet.... I'm sure that most folk would see why that has made me a little more excited than usual...quite frankly this is a MASSIVE step backwards.

**Comment by kunosee** [comment]
###### censored first words...

When you really worked 12-18 month on a software based on this library:

- where are your contributions to make this library better?
- you should have a very good insight in this library 
- you should have seen within minutes, that this change is only 8 additions and one deletion, something you can take back with 3 minutes (https://github.com/me-no-dev/ESPAsyncWebServer/commit/bed4146ec647fd1cdfd1d2485724369c92cab8e6), so i really don't see where you see  "a HUGE amount of work to re-engineer"

If such a small change in a related library makes your code unusable, you should have used your time for other things than coding.

The change is sitting before the TCP-Stack, which is completly handled by lwip. So nothing needs to be done with ACK and NAK
Yes, there is some room for improvment:

Come on, spent one or two days to fix this problem:

- create a method -bool syncWebSocketClient::_queueMessage_ , which will return information, if queueing was succesful
- extend the class constructor , so that you can set the max number of messages per queue OR a minimum heap size, which must be available to queue more messages

**Comment by cgmckeever** [comment]
THANK YOU
