### ISSUE TITLE
WebSocket setAuthentication doesn't work 

### ISSUE THREAD

**Issue by Kolsha** [me-no-dev/ESPAsyncWebServer#490]
Hi. I faced a bug that websocket authorization does not work in mobile Google chrome app (72.0.3626.101 version). I get "Disconnect" when I use setAuthentication. In the desktop version of Google chrome all works good.

**Comment by Kolsha** [comment]
Anyone?

**Comment by polaco1782** [comment]
> Anyone?

Yes, Im having the same issue. Seems the problem is on the username/password validation.

on the file AsyncWebSocket.cpp, line 1157, the code:

`if((_username != "" && _password != "") && !request->authenticate(_username.c_str(), _password.c_str()))`

seems to be the problem. If you comment out the (_username != "" && _password != "") it will ask for the credentials. I've not tested it enough, I'll try to fix it and write a patch

**Comment by Kolsha** [comment]
@me-no-dev Is this fixed?
