### ISSUE TITLE
SPIFFS with template lost original data

### ISSUE THREAD

**Issue by Ulibka68** [me-no-dev/ESPAsyncWebServer#500]
I'm use responce from file in SPIFFS with template:

```
String processor_config(const String& var)
{
 if (var == ("tick1_ON") )
      return String (5);
 .....
  return String();
}
void handle_Config(AsyncWebServerRequest *request) {
    request->send(SPIFFS, "/config2.htm", "text/html", false, processor_config);
};
```

The problem :
Original file (config2.htm) consist following CSS classes:
body,h1,.form , .item1, .label1  and others

But after processing this file with templates class defeneition ".label1" was removed from output stream (and some others class also removed)

But if I'm use simple SPIFFS answer, original file was transferred without any changes
```
void handle_Config2(AsyncWebServerRequest *request) {
    request->send(SPIFFS, "/config2.htm");
};
```

I'm provide small platformio project for Esp8266 with 4mb flash with this issue
[Spiffs Issue.zip](https://github.com/me-no-dev/ESPAsyncWebServer/files/3047682/Spiffs.Issue.zip)

**Comment by boarchuz** [comment]
I happened to be checking here because I just noticed the same problem, and this is the top issue!
Your problem is the same as mine: You have a '%' in your string to be processed that is NOT part of a template. 
The quick fix would be to create a template for the % character. For example, your css for .item1 might become:
```
.item1 {
            width: 100%PERCENT_SYMBOL%;
            margin: 5px;
            display: flex;
            flex-direction: row;
            justify-content: flex-end;
            flex-wrap: wrap;
        }
```
with a corresponding entry in your processor to return "%" for "PERCENT_SYMBOL". 

The better solution would probably be for AWS to use a more obscure character for templates since % is fairly common, and/or allow the user to send a custom one that they know won't have any conflicts.
