### ISSUE TITLE
Logout of authenticated page

### ISSUE THREAD

**Issue by Speedy2k** [me-no-dev/ESPAsyncWebServer#650]
Hi, i have a page that need login to have access to data, the problem is that i want to be able to log out before leaving so nobody else can get acess to the settings. but when i does this:

server.on("/logout", HTTP_GET, [](AsyncWebServerRequest * request){
    request->requestAuthentication();
    request->redirect("/");
  });

IT doesn't log out! if i return to this:

server.serveStatic("/advanced.html", SPIFFS, "/advanced.html").setCacheControl("max-age=600").setAuthentication((char*)loginUser.c_str(), (char*)loginPass.c_str());

It get right in without asking for password!?

**Comment by me-no-dev** [comment]
this is because the auth header is still cached and used by the browser. You have to reset this header in the browser. I've done this... seems that what you wrote should have generally worked. Maybe instead of requestAuthentication then redirect, you should do requestAuthentication in the index? or maybe another code had to be sent to the browser 40something... but unless your browser stops using the headers, you will get auth every time...

**Comment by sfranzyshen** [comment]
stale bot is not useful ... it degrades development ... please eliminate this feature from this repository ...

**Comment by sfranzyshen** [comment]
stale bot is not useful ... it degrades development ... please eliminate this feature from this repository ...
