### ISSUE TITLE
exception on sending binary data

### ISSUE THREAD

**Issue by punund** [me-no-dev/ESPAsyncWebServer#793]
I would like to avoid interpreting multipart data and send files in one chunk:

    curl --data-binary file=@myfile.bin http://esphost.local/upload

This crashes the program if the file is moderately large (30K), `onRequestBody` doesn't get called.
It would be nice to have a way of handling this.

**Comment by beyama** [comment]
I had the same issue when sending binary data from a browser. My issue was solved by setting the `content-type` header to `application/x-protobuf` instead of the default `application/x-www-form-urlencoded`. I think the default for cURL in the example from @punund is `application/x-www-form-urlencoded` as well.
