### ISSUE TITLE
On Posting Large Data onRequestBody called twice

### ISSUE THREAD

**Issue by biswaKL** [me-no-dev/ESPAsyncWebServer#872]
server.onRequestBody(handleBodyUpload);

I am trying to post a large json from POSTMAN. If the JSON is large. The **handleBodyUpload** is getting called twice.

Please help me in resolving it

**Comment by Bomexxuk** [comment]
Hi, I had the same issue yesterday. 

Yes on large files, the request execute twice because **size_t len** is maximum 251 assuming you have JSON size of 310, then the request execute twice. First you will have to covert the **uint8_t data** into a String and determine if this is the first half of you object.  As you sending JSON, the first char in the sequence will be '{' . Create a global variable where you can store the first half of the JSON string. Once you done this you will need the 2nd half of the sequence. If the first char is not '{' , add this part of the JSON to the global variable.

Once its completed use your deserializeJson method to convert your String to JSON object. Or modify the library so it takes in bigger data.

**Comment by BlueAndi** [comment]
https://github.com/me-no-dev/ESPAsyncWebServer#body-data-handling
