### ISSUE TITLE
Basic Auth not working on ESP8266 (ESP1)

### ISSUE THREAD

**Issue by mexusbg** [me-no-dev/ESPAsyncWebServer#997]
![image](https://user-images.githubusercontent.com/26608392/120823499-2b5d5000-c560-11eb-8efe-8941249f85fb.png)
```
...
const char *http_username = "admin";
const char *http_password = "admin";
AsyncWebServer server(80);
...
```

In setup: 
```
...
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request)
            {
              if (!request->authenticate(http_username, http_password))
                return request->requestAuthentication();
              request->send(200, "text/plain", "OK");
              lampOn = true;
              toggle = false;
            });
   server.begin();
...
```

In POSTMAN I get error 401. The same code worked on ESP32 a month ago. Didn't test again with ESP32

**Comment by mexusbg** [comment]
Looks like it defaults to Digest instead of Basic. Any fix?

**Comment by feraldruid22** [comment]
I would be happy to hear that as well as I have developed an Android app connecting to this and just made the server side code ESP8266 backward compatible as well and run into the same issue.

With curl a quick fix is:

`curl -v --anyauth --connect-timeout 15 -u user:pass http://url`

for curl but as I said I would prefer using the same auth method for both instead of having to rewrite/recompile my Android app now.

**Comment by feraldruid22** [comment]
Oh man this is straight out retarded.
The proper solution should be:

    if(!request->authenticate(www_username, www_password))
        return request->requestAuthentication(NULL,false);

but this seems to be broken on the ESP8266 because I get:

```
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Connection: close
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="Login Required"
< Accept-Ranges: none

```

So it is not using basic by default because its broken by default.

**Comment by feraldruid22** [comment]
I have checked out the forks here:

https://github.com/me-no-dev/ESPAsyncWebServer/network

Sadly none of them fixed this.

**Comment by githrdw** [comment]
>Looks like it defaults to Digest instead of Basic. Any fix?

Had to dive into the source code to find out how to enable base64/basic authentication.
Turns out you have to pass only one pararmeter, the base64 hash, so you have to encode that yourself (`username`:`password`).

https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/ESPAsyncWebServer.h#L224-L228

I think the above comment should also be in the readme
